# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/about.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):

    def __init__(self, app_icon, app_name, app_version, app_url):
        self._icon = app_icon
        self._name = app_name
        self._version = app_version
        self._url = app_url

        self.textTitle = None
        self.textBody = None

    def setupUi(self, dialog):
        dialog.setObjectName('About')
        dialog.resize(300, 250)

        self.verticalLayout = QtWidgets.QVBoxLayout(dialog)
        self.horizontalLayout = QtWidgets.QHBoxLayout()

        self.imageBox = QtWidgets.QLabel()
        self.imageBox.setFixedSize(QtCore.QSize(100, 100))
        self.imageBox.setScaledContents(True)
        pixmap = self._icon.pixmap(self._icon.availableSizes()[-1])
        self.imageBox.setPixmap(pixmap)
        self.horizontalLayout.addWidget(self.imageBox)

        self.textTitle = QtWidgets.QLabel()
        self.textTitle.setTextFormat(QtCore.Qt.RichText)
        self.textTitle.setScaledContents(True)
        self.horizontalLayout.addWidget(self.textTitle)

        self.verticalLayout.addLayout(self.horizontalLayout)

        self.textBody = QtWidgets.QLabel(dialog)
        self.textBody.setTextFormat(QtCore.Qt.RichText)
        self.textBody.setScaledContents(True)
        self.textBody.setWordWrap(True)
        self.textBody.setOpenExternalLinks(True)

        self.verticalLayout.addWidget(self.textBody)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate('About', 'About'))
        self.textTitle.setText('<html>'
                               '<head/>'
                               '<body>'
                               '<b>{0} v{1}</b>'
                               '<p>by Jacob Jewett</p>'
                               '</body>'
                               '</html>'.format(self._name, self._version))
        self.textBody.setText('<html>'
                              '<head/>'
                              '<body>'
                              '<a href="{0}">{0}</a>'
                              '<p>Thank you to:<br/>'
                              '- PyMuPDF (for the PDF I/O library)<br/>'
                              '- PyQt5 (for this portable GUI framework)<br/>'
                              '- pyinstaller (for an excellent Python packaging solution)<br/>'
                              '- Mr. Garcia (for being an awesome math teacher)<br/>'
                              '- Jak544 (for testing)</p>'
                              '</body>'
                              '</html>'.format(self._url))
